### ISSUE TITLE
Handle shorthand values (with underscore)

### ISSUE THREAD

**Issue by phucbm** [phucbm/tailwindcss-style-props#1]
Class `style-[--radius=300px_20px_20px_300px]`

Output ❌

```css
.style-\[--radius\=300px_20px_20px_300px\] {
  --radius:300px_20px_20px_300px;
}
```

Expected ✅

```css
.style-\[--radius\=300px_20px_20px_300px\] {
  --radius:300px 20px 20px 300px;
}
```
